### PR TITLE
fixed discrepancy with ontology resource name

### PR DESCRIPTION
**Pull request by dmellish99**
removed /ontology from naming scheme and queries.

### CODE REVIEW

**Comment by dmellish99** [comment]
we also removed errors in the files **'ontology-updated.ttl'** 
and **'data-updated.ttl'**

**Comment by rgcmme** [comment]
There are conflicts in the pull request

**Comment by dmellish99** [comment]
Hi, we reviewed the conflicts and it is believed that the conflicts are due to errors in  'ontology-updated.ttl'
and 'data-updated.ttl' produced by github. 
example

**Comment by dmellish99** [comment]
However, this should not be there and we should overwrite with the clean files.

**Comment by rgcmme** [comment]
You can solve the conflicts locally in the files.

**Comment by dmellish99** [comment]
sorry i'm kind of confused, how would i do this?

**Comment by dmellish99** [comment]
I see this error: 
image

**Comment by rgcmme** [comment]
In your local files you should have the conflicts indicated as in the first image. Just remove all the things that should not be there and resolve the conflict.

Or copy your latest files, restore from the repository the files and apply there the changes.

**Comment by dmellish99** [comment]
would I need to switch to the direct repository https://github.com/FacultadInformatica-LinkedData/Curso2024-2025-ODKG? I can't see any conflicts unfortunately in my local repository.

**Comment by dmellish99** [comment]
do you have any office hours available today or tomorrow? I don' think this is a difficult issue but the problem is that I am forking from the class repository and I cannot see any conflicts on my end.

**Pull request closed without merging**
