### PR TITLE
Hands-on assignment 1: Group10

### PR DESCRIPTION
**Pull request by sheyls**

### CODE REVIEW

**Comment by rgcmme** [comment]
There is something strange with this pull request because I cannot see the files being changed.
In any case, it seems that you are using a group name that already exists. Can you update it and let's see if it can be seen correctly?

**Comment by sheyls** [comment]
Could you merge it now? I've updated the name to '10'

**Comment by rgcmme** [comment]
You are adding the group 10 information but you are removing all the files from group 1.
Let's close this pull request and make another one with only the changes required.

**Comment by sheyls** [comment]
Ok. I did another PR already

**Pull request closed without merging**
