### PR TITLE
HO2-Group01

### PR DESCRIPTION
**Pull request by Barba32**
Here is the assignment 2 of the Group01

### CODE REVIEW

**Comment by rgcmme** [comment]
You are updating one file from the Templates directory

**Comment by Barba32** [comment]
Sorry, it was my fault. I made a fetch before creating the branch and when
I created the branch I committed the template accidentally. I have to
remake the pull request?

Thank you!

**Comment by dgarijo** [comment]
no, but you have to restore the file

**Comment by Barba32** [comment]
But in my fork or where? The file that I'm updating in the templates is the
original one, without commits.
Where do I have to make the git restore?

**Comment by Barba32** [comment]
Ok, I think I understand what I have to do. Do you want me to restore the commit I made to the Templates folder?

**Comment by rgcmme** [comment]
Yes, just restore the updates to that file.

**Comment by Barba32** [comment]
Perfect, I've just restored the file so is correct now.

**Pull request merged**
