### PR TITLE
HO3-Group05

### PR DESCRIPTION
**Pull request by dmellish99**
Adding materials for 3rd assignment of hands on
Also modifying existing materials for 2nd assignment.

### CODE REVIEW

**Comment by rgcmme** [comment]
You are creating a data-clean directory out of your hands-on directory.

**Comment by dmellish99** [comment]
Hi, yes my apologies. We just wanted to have all of the files used together to keep it organized and repeatable. We asked permission from Professor Calleja to do the data cleaning in python and he had no issues with it.

**Comment by dmellish99** [comment]
If you prefer I can remove the additional directory/extra files

**Comment by rgcmme** [comment]
Either move them to your directory or remove them; but they cannot be in the parent directory

**Comment by dmellish99** [comment]
i believe it should be fixed now

**Comment by rgcmme** [comment]
Perfect!

**Pull request merged**
