### PR TITLE
Hands-on assignment-1 Group-10

### PR DESCRIPTION
**Pull request by sheyls**

### CODE REVIEW

**Comment by rgcmme** [comment]
I don't know what can be happening with your pull requests, because I cannot see what changes are being done in the repository. In this one I see that 30 files are changed, but not which of them, which suggests that something weird is happening. The pull request for assignment 2 shows 43 changes, which is not normal also.
How are you making the commits and pull requests?

**Comment by sheyls** [comment]
This problem is with the GitHub preview. One of the team members also experienced that she couldn’t make the commit because the files were not being previewed. The only thing that might be unusual in the commit is that we initially had 25 CSV files, and then there are 27 in the second commit, but we modified them and deleted the previous 25. That explains the reported changes. The issue is not with the commit or the PR, but rather with GitHub's support for so many changes. If you prefer, we can delete everything and leave just one CSV.

**Comment by rgcmme** [comment]
Then, I propose the following. Make one pull request adding only one file and, once it is accepted, make another one with the rest of the files.

**Comment by sheyls** [comment]
I already remove 24 files, it's okey or should I make another branch?

**Pull request merged**
